// Code generated by cmd/cgo; DO NOT EDIT.

//line main.go:1:1
package main

// double sum(int a, float b);
import _ "unsafe"

//export sum
func sum(a  /*line :7:12*/_Ctype_int /*line :7:17*/, b  /*line :7:21*/_Ctype_float /*line :7:28*/)  /*line :7:30*/_Ctype_double /*line :7:38*/ {
	return  /*line :8:9*/_Ctype_double /*line :8:17*/(a) +  /*line :8:23*/_Ctype_double /*line :8:31*/(b)
}

func main() {}
