"""""""""""""""""""""""""""""""""""""""""""""""""
" @author Shadowman
" @version 1.0.0
" @license MIT License
" @link https://github.com/JShadowMan/
"""""""""""""""""""""""""""""""""""""""""""""""""
set nocompatible

