// Code generated by cmd/cgo; DO NOT EDIT.

//line main.go:1:1
package main

/*
static double sum(int a, float b) {
	return (double) a + (double) b;
}
*/
import _ "unsafe"
import "fmt"

func main() {
	fmt.Println(( /*line :12:14*/_Cfunc_sum /*line :12:18*/)(1, 2.0))
}
