/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_wjiec_nativec_NativeC */

#ifndef _Included_com_github_wjiec_nativec_NativeC
#define _Included_com_github_wjiec_nativec_NativeC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_wjiec_nativec_NativeC
 * Method:    say
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_wjiec_nativec_NativeC_say__
  (JNIEnv *, jobject);

/*
 * Class:     com_github_wjiec_nativec_NativeC
 * Method:    say
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_github_wjiec_nativec_NativeC_say__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
